# Site settings
title: Yong blog
email:
description: "..."
baseurl: ""
url: "https://yongsingyou.github.io"
twitter_username:
github_username: yongsingyou

# Build settings
markdown: kramdown
permalink: pretty

highlighter: rouge
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge
